=== nikabenz/freeit-start-java/notebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="notes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="note" type="note" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="note">
        <xs:sequence>
            <xs:element name="data" type="xs:string"/>
            <xs:element name="topic" type="xs:string"/>
            <xs:element name="activities">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="activity" type="activity" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="activity">
        <xs:sequence>
            <xs:element name="time" type="xs:string"/>
            <xs:element name="type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== nikabenz/freeit-start-java/notebook.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="notebook.xsd">
    <note>
        <data>02.09.2022</data>
        <topic>train</topic>
        <activities>
            <activity>
                <time>08:00</time>
                <type>jogging</type>
            </activity>
            <activity>
                <time>11:00</time>
                <type>fitness</type>
            </activity>
            <activity>
                <time>12:00</time>
                <type>water poll</type>
            </activity>
            <activity>
                <time>20:00</time>
                <type>tae bo</type>
            </activity>
            <activity>
                <time>20:30</time>
                <type>karate</type>
            </activity>
            <activity>
                <time>21:00</time>
                <type>stretch</type>
            </activity>
        </activities>
    </note>
    <note>
        <data>03.09.2022</data>
        <topic>learn</topic>
        <activities>
            <activity>
                <time>08:00</time>
                <type>English</type>
            </activity>
            <activity>
                <time>12:00</time>
                <type>Java</type>
            </activity>
            <activity>
                <time>20:00</time>
                <type>German</type>
            </activity>
        </activities>
    </note>
    <note>
        <data>04.09.2022</data>
        <topic>work</topic>
        <activities>
            <activity>
                <time>08:00</time>
                <type>teaching</type>
            </activity>
        </activities>
    </note>
    <note>
        <data>05.09.2022</data>
        <topic>work</topic>
        <activities>
            <activity>
                <time>08:00</time>
                <type>teaching</type>
            </activity>
        </activities>
    </note>
    <note>
        <data>06.09.2022</data>
        <topic>relax</topic>
        <activities>
            <activity>
                <time>12:00</time>
                <type>walk in the park</type>
            </activity>
            <activity>
                <time>16:00</time>
                <type>routine</type>
            </activity>
        </activities>
    </note>
</notes>
